- name: Install docker
  yum:
    name: docker
    state: present

- name: Start docker
  service:
    name: docker
    state: started

- name: Create docker container
  shell: docker run -u root --rm -d -p 8080:8080 -p 50000:50000 -v jenkins-data:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock jenkinsci/blueocean
  args:
    executable: /bin/bash

- name: Create jenkins_home sym link
  file:
    src: /var/lib/docker/volumes/jenkins-data/_data/
    dest: /var/jenkins_home
    state: link
